### ISSUE TITLE
Use MF2 parser to identify webmention types

### ISSUE THREAD

**Issue by barryf** [barryf/transformative#1]
When receiving a webmention, Transformative uses Nokogiri to scan through and find `a.u-like-of` links within the source HTML. 

@myfreeweb's [sweetroll](https://github.com/myfreeweb/sweetroll) uses `rel=like-of` and links within `.u-like-of` blocks. Webmentions from Greg that are correctly marked-up as likes are currently treated as plain mentions. Their reposts and replies are probably treated the same way.

The code should detect webmention types using the (new) Ruby MF2 parser.

(NB I've switched to the new MF2 parser and can now pick up their relative URLs and store as absolutes.)

**Comment by barryf** [comment]
@myfreeweb This should now be fixed in 676176376ec347b832d0bfb692227e3996e0efe4. Would you mind sending another like to help me test?

**Comment by valpackett** [comment]
yeah it works now! even delete-undelete (http 410) worked. nice

**Comment by barryf** [comment]
Wonderful! Many thanks for your help again, Greg.
