### ISSUE TITLE
Heroku deploy button?

### ISSUE THREAD

**Issue by Lewiscowles1986** [barryf/transformative#11]
Would you be open to a PR for a one-click heroku deploy?

**Comment by barryf** [comment]
Well it’s not really in a good state to be a one-click solution. There are quite a few hard-coded personalisations for my own site that would need to be extracted. It’s very much rough round the edges!

You’re welcome to fork and customise — in fact that’s what @gerwitz originally did with https://github.com/gerwitz/sitewriter.
